services:
  node:
    command: npm run dev
    build:
      context: ./
      dockerfile: battleNode.dockerfile
      args:
        HTTP_PORT: 3055
    environment:
        HTTP_PORT: 3055
        METRIC_BASIC_AUTH_USER: "abcd"
        METRIC_BASIC_AUTH_PASS: "efgh"
    networks:
        - app

  proxy:
    command: npm run dev
    build:
      context: ./
      dockerfile: battleProxy.dockerfile
      args:
        HTTP_PORT: 3057
    environment:
        HTTP_PORT: 3057
        METRIC_BASIC_AUTH_USER: "abcd"
        METRIC_BASIC_AUTH_PASS: "efgh"
    ports:
        - 3057:3057
    networks:
        - app

networks:
  app:
    driver: bridge
