import { LEVEL_ONE_LOOT_TABLE, LEVEL_ONE_MONSTERS } from "./level1"
import { LEVEL_TEN_LOOT_TABLE, LEVEL_TEN_MONSTERS } from "./level10"
import { LEVEL_ELEVEN_LOOT_TABLE, LEVEL_ELEVEN_MONSTERS } from "./level11"
import { LEVEL_TWELVE_LOOT_TABLE, LEVEL_TWELVE_MONSTERS } from "./level12"
import { LEVEL_THIRTEEN_LOOT_TABLE, LEVEL_THIRTEEN_MONSTERS } from "./level13"
import { LEVEL_FOURTEEN_LOOT_TABLE, LEVEL_FOURTEEN_MONSTERS } from "./level14"
import { LEVEL_FIFTEEN_LOOT_TABLE, LEVEL_FIFTEEN_MONSTERS } from "./level15"
import { LEVEL_SIXTEEN_LOOT_TABLE, LEVEL_SIXTEEN_MONSTERS } from "./level16"
import { LEVEL_SEVENTEEN_LOOT_TABLE, LEVEL_SEVENTEEN_MONSTERS } from "./level17"
import { LEVEL_EIGHTEEN_LOOT_TABLE, LEVEL_EIGHTEEN_MONSTERS } from "./level18"
import { LEVEL_NINETEEN_LOOT_TABLE, LEVEL_NINETEEN_MONSTERS } from "./level19"
import { LEVEL_TWO_LOOT_TABLE, LEVEL_TWO_MONSTERS } from "./level2"
import { LEVEL_TWENTY_LOOT_TABLE, LEVEL_TWENTY_MONSTERS } from "./level20"
import { LEVEL_TWENTY_ONE_LOOT_TABLE, LEVEL_TWENTY_ONE_MONSTERS } from "./level21"
import { LEVEL_TWENTY_TWO_LOOT_TABLE, LEVEL_TWENTY_TWO_MONSTERS } from "./level22"
import { LEVEL_TWENTY_THREE_LOOT_TABLE, LEVEL_TWENTY_THREE_MONSTERS } from "./level23"
import { LEVEL_TWENTY_FOUR_LOOT_TABLE, LEVEL_TWENTY_FOUR_MONSTERS } from "./level24"
import { LEVEL_TWENTY_FIVE_LOOT_TABLE, LEVEL_TWENTY_FIVE_MONSTERS } from "./level25"
import { LEVEL_TWENTY_SIX_LOOT_TABLE, LEVEL_TWENTY_SIX_MONSTERS } from "./level26"
import { LEVEL_TWENTY_SEVEN_LOOT_TABLE, LEVEL_TWENTY_SEVEN_MONSTERS } from "./level27"
import { LEVEL_THREE_LOOT_TABLE, LEVEL_THREE_MONSTERS } from "./level3"
import { LEVEL_FOUR_LOOT_TABLE, LEVEL_FOUR_MONSTERS } from "./level4"
import { LEVEL_FIVE_LOOT_TABLE, LEVEL_FIVE_MONSTERS } from "./level5"
import { LEVEL_SIX_LOOT_TABLE, LEVEL_SIX_MONSTERS } from "./level6"
import { LEVEL_SEVEN_LOOT_TABLE, LEVEL_SEVEN_MONSTERS } from "./level7"
import { LEVEL_EIGHT_LOOT_TABLE, LEVEL_EIGHT_MONSTERS } from "./level8"
import { LEVEL_NINE_LOOT_TABLE, LEVEL_NINE_MONSTERS } from "./level9"

console.log("exporting level/index.js TABLE_LIST")

export const TABLE_LIST = {
    1: LEVEL_ONE_LOOT_TABLE,
    2: LEVEL_TWO_LOOT_TABLE,
    3: LEVEL_THREE_LOOT_TABLE,
    4: LEVEL_FOUR_LOOT_TABLE,
    5: LEVEL_FIVE_LOOT_TABLE,
    6: LEVEL_SIX_LOOT_TABLE,
    7: LEVEL_SEVEN_LOOT_TABLE,
    8: LEVEL_EIGHT_LOOT_TABLE,
    9: LEVEL_NINE_LOOT_TABLE,
    10: LEVEL_TEN_LOOT_TABLE,
    11: LEVEL_ELEVEN_LOOT_TABLE,
    12: LEVEL_TWELVE_LOOT_TABLE,
    13: LEVEL_THIRTEEN_LOOT_TABLE,
    14: LEVEL_FOURTEEN_LOOT_TABLE,
    15: LEVEL_FIFTEEN_LOOT_TABLE,
    16: LEVEL_SIXTEEN_LOOT_TABLE,
    17: LEVEL_SEVENTEEN_LOOT_TABLE,
    18: LEVEL_EIGHTEEN_LOOT_TABLE,
    19: LEVEL_NINETEEN_LOOT_TABLE,
    20: LEVEL_TWENTY_LOOT_TABLE,
    21: LEVEL_TWENTY_ONE_LOOT_TABLE,
    22: LEVEL_TWENTY_TWO_LOOT_TABLE,
    23: LEVEL_TWENTY_THREE_LOOT_TABLE,
    24: LEVEL_TWENTY_FOUR_LOOT_TABLE,
    25: LEVEL_TWENTY_FIVE_LOOT_TABLE,
    26: LEVEL_TWENTY_SIX_LOOT_TABLE,
    27: LEVEL_TWENTY_SEVEN_LOOT_TABLE
}

export const MONSTER_LIST = {
    1: LEVEL_ONE_MONSTERS,
    2: LEVEL_TWO_MONSTERS,
    3: LEVEL_THREE_MONSTERS,
    4: LEVEL_FOUR_MONSTERS,
    5: LEVEL_FIVE_MONSTERS,
    6: LEVEL_SIX_MONSTERS,
    7: LEVEL_SEVEN_MONSTERS,
    8: LEVEL_EIGHT_MONSTERS,
    9: LEVEL_NINE_MONSTERS,
    10: LEVEL_TEN_MONSTERS,
    11: LEVEL_ELEVEN_MONSTERS,
    12: LEVEL_TWELVE_MONSTERS,
    13: LEVEL_THIRTEEN_MONSTERS,
    14: LEVEL_FOURTEEN_MONSTERS,
    15: LEVEL_FIFTEEN_MONSTERS,
    16: LEVEL_SIXTEEN_MONSTERS,
    17: LEVEL_SEVENTEEN_MONSTERS,
    18: LEVEL_EIGHTEEN_MONSTERS,
    19: LEVEL_NINETEEN_MONSTERS,
    20: LEVEL_TWENTY_MONSTERS,
    21: LEVEL_TWENTY_ONE_MONSTERS,
    22: LEVEL_TWENTY_TWO_MONSTERS,
    23: LEVEL_TWENTY_THREE_MONSTERS,
    24: LEVEL_TWENTY_FOUR_MONSTERS,
    25: LEVEL_TWENTY_FIVE_MONSTERS,
    26: LEVEL_TWENTY_SIX_MONSTERS,
    27: LEVEL_TWENTY_SEVEN_MONSTERS
}
