import { LEVEL_ONE_MONSTERS, LEVEL_ONE_LOOT_TABLE } from './level1';
import { LEVEL_TWO_MONSTERS, LEVEL_TWO_LOOT_TABLE } from './level2';
import { LEVEL_THREE_MONSTERS, LEVEL_THREE_LOOT_TABLE } from './level3';
import { LEVEL_FOUR_MONSTERS, LEVEL_FOUR_LOOT_TABLE } from './level4';
import { LEVEL_FIVE_MONSTERS, LEVEL_FIVE_LOOT_TABLE } from './level5';
import { LEVEL_SIX_MONSTERS, LEVEL_SIX_LOOT_TABLE } from './level6';
import { LEVEL_SEVEN_MONSTERS, LEVEL_SEVEN_LOOT_TABLE } from './level7';
import { LEVEL_EIGHT_MONSTERS, LEVEL_EIGHT_LOOT_TABLE } from './level8';

export const TABLE_LIST = {
  1: LEVEL_ONE_LOOT_TABLE,
  2: LEVEL_TWO_LOOT_TABLE,
  3: LEVEL_THREE_LOOT_TABLE,
  4: LEVEL_FOUR_LOOT_TABLE,
  5: LEVEL_FIVE_LOOT_TABLE,
  6: LEVEL_SIX_LOOT_TABLE,
  7: LEVEL_SEVEN_LOOT_TABLE,
  8: LEVEL_EIGHT_LOOT_TABLE
}

export const MONSTER_LIST = {
  1: LEVEL_ONE_MONSTERS,
  2: LEVEL_TWO_MONSTERS,
  3: LEVEL_THREE_MONSTERS,
  4: LEVEL_FOUR_MONSTERS,
  5: LEVEL_FIVE_MONSTERS,
  6: LEVEL_SIX_MONSTERS,
  7: LEVEL_SEVEN_MONSTERS,
  8: LEVEL_EIGHT_MONSTERS
}
