import { LEVEL_ONE_MONSTERS, LEVEL_ONE_LOOT_TABLE } from './level1';
import { LEVEL_TWO_MONSTERS, LEVEL_TWO_LOOT_TABLE } from './level2';
import { LEVEL_THREE_MONSTERS, LEVEL_THREE_LOOT_TABLE } from './level3';
import { LEVEL_FOUR_MONSTERS, LEVEL_FOUR_LOOT_TABLE } from './level4';
import { LEVEL_FIVE_MONSTERS, LEVEL_FIVE_LOOT_TABLE } from './level5';

export const TABLE_LIST = {
  1: LEVEL_ONE_LOOT_TABLE,
  2: LEVEL_TWO_LOOT_TABLE,
  3: LEVEL_THREE_LOOT_TABLE,
  4: LEVEL_FOUR_LOOT_TABLE,
  5: LEVEL_FIVE_LOOT_TABLE
}

export const MONSTER_LIST = {
  1: LEVEL_ONE_MONSTERS,
  2: LEVEL_TWO_MONSTERS,
  3: LEVEL_THREE_MONSTERS,
  4: LEVEL_FOUR_MONSTERS,
  5: LEVEL_FIVE_MONSTERS
}
